# Generated by Django 4.1.1 on 2022-10-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Day', models.CharField(max_length=20)),
                ('Toner', models.IntegerField()),
                ('TonerSpent', models.IntegerField()),
                ('isSunday', models.IntegerField()),
                ('isHoliday', models.IntegerField()),
                ('isPaperCame', models.IntegerField()),
                ('PaperQuantityCame', models.IntegerField()),
                ('isPaperSent', models.IntegerField()),
                ('PaperQuantitySent', models.IntegerField()),
                ('isTonerCame', models.IntegerField()),
                ('isTonerSent', models.IntegerField()),
                ('TonerQuantityCame', models.IntegerField()),
                ('TonerQuantitySent', models.IntegerField()),
                ('isItemsCame', models.IntegerField()),
                ('ItemsInfo', models.CharField(max_length=200)),
                ('BlackMachineReading1', models.IntegerField()),
                ('BlackMachineReading2', models.IntegerField()),
                ('ColourMachineReading1', models.IntegerField()),
                ('ColourMachineReading2', models.IntegerField()),
                ('BlackCopies', models.IntegerField()),
                ('ColourCopies', models.IntegerField()),
                ('B2bCopies', models.IntegerField()),
                ('PaperSheet', models.IntegerField()),
                ('PaperPresentToday', models.IntegerField()),
                ('PaperSoldToday', models.IntegerField()),
                ('Bindings', models.IntegerField()),
                ('Expenses', models.IntegerField()),
                ('TodayStayDetail', models.CharField(max_length=200)),
                ('PastStayDetail', models.CharField(max_length=200)),
                ('PastSoldDetail', models.CharField(max_length=200)),
                ('TodayStayingCopies', models.IntegerField()),
                ('TodayStayingMoney', models.IntegerField()),
                ('OldStayingMoney', models.IntegerField()),
                ('OldStayingCopies', models.IntegerField()),
                ('GoneCopiesPast', models.IntegerField()),
                ('GoneMoneyPast', models.IntegerField()),
                ('NotesToday', models.CharField(max_length=200)),
                ('CashIncome', models.IntegerField()),
                ('PaytmIncome', models.IntegerField()),
                ('TotalIncome', models.IntegerField()),
                ('OpeningBalance', models.IntegerField()),
                ('NetProfit', models.IntegerField()),
                ('GetTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LabourExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Day', models.CharField(max_length=10)),
                ('GetTime', models.IntegerField()),
                ('TajPresent', models.IntegerField()),
                ('TajExpense', models.IntegerField()),
                ('NoorPresent', models.IntegerField()),
                ('NoorExpense', models.IntegerField()),
                ('isTajHalfDay', models.IntegerField()),
                ('isNoorHalfDay', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RateSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bata1', models.IntegerField(default=90)),
                ('bata2', models.IntegerField(default=70)),
                ('food', models.IntegerField(default=150)),
                ('tajSalary', models.DecimalField(decimal_places=2, default=633.33, max_digits=9)),
                ('noorSalary', models.DecimalField(decimal_places=2, default=466.66, max_digits=9)),
                ('assanSalary', models.DecimalField(decimal_places=2, default=466.66, max_digits=9)),
                ('maniSalary', models.DecimalField(decimal_places=2, default=333.33, max_digits=9)),
                ('rasheedSalary', models.DecimalField(decimal_places=2, default=333.33, max_digits=9)),
                ('paperRate', models.DecimalField(decimal_places=2, default=0.5, max_digits=9)),
                ('tonerRate', models.DecimalField(decimal_places=2, default=800.0, max_digits=9)),
                ('singleRate', models.DecimalField(decimal_places=2, default=1.25, max_digits=9)),
                ('b2bRate', models.DecimalField(decimal_places=2, default=0.85, max_digits=9)),
                ('copiesPerToner', models.IntegerField(default=19000)),
                ('tpmRent', models.DecimalField(decimal_places=2, default=516.66, max_digits=9)),
                ('kdmRent', models.DecimalField(decimal_places=2, default=800.0, max_digits=9)),
                ('currentBillKdm', models.IntegerField(default=110)),
                ('currentBillTpm', models.IntegerField(default=110)),
            ],
        ),
    ]
