# Generated by Django 3.2.16 on 2023-03-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountKdm', '0004_auto_20230304_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyentrykdm',
            name='NoorPresent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='monthlyentrykdm',
            name='TajPresent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
    ]
