# Generated by Django 3.2.16 on 2023-03-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountKdm', '0005_auto_20230304_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyentrykdm',
            name='PaperSent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
