# Generated by Django 3.2.16 on 2023-03-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountKdm', '0007_auto_20230306_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthString', models.CharField(max_length=200)),
                ('MonthNum', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Paper', models.IntegerField()),
                ('PaperPending', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('SalaryPending', models.IntegerField()),
                ('Toner', models.IntegerField()),
                ('TonerPending', models.IntegerField()),
                ('Kl', models.IntegerField()),
                ('KlPending', models.IntegerField()),
                ('Vadapalani', models.IntegerField()),
                ('VadapalaniPending', models.IntegerField()),
                ('David', models.IntegerField()),
                ('DavidPending', models.IntegerField()),
                ('RentTpm', models.IntegerField()),
                ('RentTpmPending', models.IntegerField()),
                ('RentAshref', models.IntegerField()),
                ('RentAshrefPending', models.IntegerField()),
                ('RentNoushad', models.IntegerField()),
                ('RentNoushadPending', models.IntegerField()),
                ('Rent2', models.IntegerField()),
                ('Rent2Pending', models.IntegerField()),
                ('Current', models.IntegerField()),
                ('CurrentPending', models.IntegerField()),
                ('Others', models.IntegerField()),
                ('OthersPending', models.IntegerField()),
            ],
        ),
    ]
