# Generated by Django 3.2.16 on 2023-03-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountKdm', '0008_predictiondata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictiondata',
            name='MonthNum',
        ),
    ]
