# Generated by Django 3.2.16 on 2023-03-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountTpm', '0003_monthlyentrytpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyentrytpm',
            name='Month',
            field=models.CharField(max_length=200),
        ),
    ]
