# Generated by Django 3.2.16 on 2023-03-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopAccountTpm', '0006_monthlyentrytpm_papersent'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyentrytpm',
            name='isEdited',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
