# Generated by Django 4.1.1 on 2022-10-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('DateString', models.CharField(max_length=20)),
                ('MonthString', models.CharField(max_length=20)),
                ('YearString', models.CharField(max_length=20)),
                ('Grocerry', models.IntegerField()),
                ('Entertainment', models.IntegerField()),
                ('Maintanence', models.IntegerField()),
                ('ShopCurrentBill', models.IntegerField()),
                ('HomeCurrentBill', models.IntegerField()),
                ('PaperCost', models.IntegerField()),
                ('BlackTonerCost', models.IntegerField()),
                ('ColourTonerCost', models.IntegerField()),
                ('BlackMachineMaintanence', models.IntegerField()),
                ('ColourMachineMaintanence', models.IntegerField()),
                ('MoneyDeposit', models.IntegerField()),
                ('PaytmExpense', models.IntegerField()),
                ('CashExpense', models.IntegerField()),
                ('TotalExpense', models.IntegerField()),
                ('TotalProfit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RateSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShahulSalary', models.DecimalField(decimal_places=2, default=1466.66, max_digits=9)),
                ('VeperyIncome', models.DecimalField(decimal_places=2, default=1266.66, max_digits=9)),
                ('VaadagaiIncome', models.DecimalField(decimal_places=2, default=233.33, max_digits=9)),
                ('CurrentBill', models.DecimalField(decimal_places=2, default=83.33, max_digits=9)),
                ('HomeLoan', models.DecimalField(decimal_places=2, default=1066.66, max_digits=9)),
            ],
        ),
    ]
