# Generated by Django 4.1.1 on 2022-10-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountexpenses',
            name='Bindings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountexpenses',
            name='Others',
            field=models.IntegerField(default=0),
        ),
    ]
